### ISSUE TITLE
Redo default config.ini per microservice

### ISSUE THREAD

**Issue by blankdots** [neicnordic/LocalEGA#3]
### Description
Default config.ini is out of date we need to update it, or remove it the requirement to have it that specific file.
We should keep the read of the file.

Split config file per microservice

### Definition of Done
Each microservice has its own separate configuration files but Env vars can still be used

### How to test
Integration tests pass as well as e2e test.

**Comment by dtitov** [comment]
I really support the idea of getting rid of `conf.ini` (and `keys.ini`) and replacing them with environment variables configuration, because it makes rolling updates complicated. 

Currently, it’s used as a configuration source for our Python microservices. And it contains configuration *for all of them*. Now, there's a new version of some component released and we introduce one new property to this file for one of those microservices. How do we get updated `conf.ini`? If we re-execute bootstrapping, it will be overridden completely. So, it seems, that we have to manually generate only new property and insert it into the file. Which is a bit cumbersome, because we will have to do it by hands…

**Comment by blankdots** [comment]
`verify`, `ingest` and maybe `finalizer` components failed to start when configured via ENVs. Puting the same config in a file worked so that's why I went that way for M7.
It mainly boils down to the fact that the configs for RabbitMQ changed to use a URL format which is a p.i.t.a. to work with.

**Comment by blankdots** [comment]
related to changes that will be integrated soon from upstream. Need to recheck after changes are merged.
